# Generated by Django 4.0.5 on 2022-09-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_area_remove_profile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_kwsstaff',
        ),
    ]
