# Generated by Django 4.0.3 on 2022-07-21 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0008_jsonfield_and_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformationProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.process')),
                ('request_type', models.CharField(choices=[('New User Account', 'New User Account'), ('Modify Access Permission', 'Modify Access Permission'), ('Update Contact Information', 'Update Contact Information')], max_length=30)),
                ('last', models.CharField(max_length=30)),
                ('first', models.CharField(max_length=30)),
                ('middle', models.CharField(max_length=30)),
                ('salutation', models.CharField(max_length=30)),
                ('user_type', models.CharField(choices=[('RMS Manager/Approver', 'RMS Manager/Approver'), ('User', 'User')], max_length=30)),
                ('temporary_staff', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('est_no', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('station', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('area', models.CharField(default='SOUTHERN', max_length=30)),
                ('date', models.DateField()),
                ('date_submitted', models.DateField(default=datetime.datetime.now)),
                ('date_completed', models.DateField(default=datetime.datetime.now)),
                ('ICT_Authority_name', models.CharField(max_length=30)),
                ('ICT_Approve', models.BooleanField(default=False)),
                ('date_approved_by_ict', models.DateField(null=True)),
                ('ICTAuthority_email', models.EmailField(max_length=254)),
                ('HOD_name', models.CharField(max_length=30)),
                ('HOD_approve', models.BooleanField(default=False)),
                ('date_approved_by_department_head', models.DateField(null=True)),
                ('HOD_email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
