# Generated by Django 4.0.3 on 2022-07-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0008_jsonfield_and_artifact'),
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralInformationProcess',
            new_name='RMSGeneralInformationProcess',
        ),
    ]
