# Generated by Django 4.0.3 on 2022-07-22 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_rename_generalinformationprocess_rmsgeneralinformationprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='HOD_approve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='HOD_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='HOD_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='ICTAuthority_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='ICT_Approve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='ICT_Authority_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='date_approved_by_department_head',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='date_completed',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='date_submitted',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
