# Generated by Django 4.0.3 on 2022-07-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_rmsgeneralinformationprocess_hod_approve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='date_approved_by_department_head',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='date_approved_by_ict',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
