# Generated by Django 4.0 on 2022-07-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_rmsgeneralinformationprocess_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='temporary_staff',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='user_type',
            field=models.CharField(choices=[('RMS Manager/Approver', 'RMS Manager/Approver'), ('User', 'User')], default='User', max_length=30),
        ),
    ]
