# Generated by Django 4.0 on 2022-07-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_rmsgeneralinformationprocess_ict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='ICT',
            field=models.CharField(blank=True, choices=[('Systems Administrator', 'Systems Administrator'), ('Senior Management', 'Senior Management')], max_length=50, null=True),
        ),
    ]
