# Generated by Django 4.0 on 2022-07-28 04:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_alter_rmsgeneralinformationprocess_ict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='ICT',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Systems Administrator', 'Systems Administrator'), ('Senior Management', 'Senior Management')], max_length=50, null=True),
        ),
    ]
