# Generated by Django 4.0 on 2022-07-28 05:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_alter_rmsgeneralinformationprocess_ict'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmsgeneralinformationprocess',
            name='CUSTOMER_SERVICE',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Customer Service Officers', 'Customer Service Officers'), ('Customer Service Users', 'Customer Service Users'), ('Checker', 'Checker'), ('Entry Clerk', 'Entry Clerk'), ('Purchase Clerk', 'Purchase Clerk'), ('Usher', 'Usher')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rmsgeneralinformationprocess',
            name='FINANCE',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Finance Mananger', 'Finance Mananger'), ('Finance Executive', 'Finance Executive')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rmsgeneralinformationprocess',
            name='INTERNAL_AUDIT',
            field=models.CharField(blank=True, choices=[('Internal Auditor', 'Internal Auditor'), ('None', 'None')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rmsgeneralinformationprocess',
            name='MARKETING',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Marketing Officers', 'Marketing Officers'), ('Marketing Executive', 'Marketing Executive')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rmsgeneralinformationprocess',
            name='PARKS_AND_RESERVES',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ranger', 'Ranger'), ('Park Management', 'Park Management')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rmsgeneralinformationprocess',
            name='REVENUE_PROTECTION_UNIT',
            field=models.CharField(blank=True, choices=[('RPU', 'RPU'), ('None', 'None')], max_length=50, null=True),
        ),
    ]
