# Generated by Django 4.0 on 2022-07-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_rmsgeneralinformationprocess_customer_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='INTERNAL_AUDIT',
            field=models.CharField(blank=True, choices=[('Internal Auditor', 'Internal Auditor'), ('None', 'None')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='REVENUE_PROTECTION_UNIT',
            field=models.CharField(blank=True, choices=[('RPU', 'RPU'), ('None', 'None')], default='None', max_length=50, null=True),
        ),
    ]
