# Generated by Django 4.0 on 2022-07-28 05:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0011_alter_rmsgeneralinformationprocess_internal_audit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmsgeneralinformationprocess',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 7, 28, 5, 57, 16, 753285, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rmsgeneralinformationprocess',
            name='Full_Name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 5, 57, 30, 430666, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rmsgeneralinformationprocess',
            name='Signature',
            field=models.EmailField(default=datetime.datetime(2022, 7, 28, 5, 57, 47, 701286, tzinfo=utc), help_text='Enter Your email to digitally sign', max_length=254),
            preserve_default=False,
        ),
    ]
