# Generated by Django 4.0 on 2022-08-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0012_rmsgeneralinformationprocess_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='HOD_email',
            field=models.EmailField(blank=True, help_text='Enter Your email to digitally sign', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='ICTAuthority_email',
            field=models.EmailField(blank=True, help_text='Enter Your email to digitally sign', max_length=254, null=True),
        ),
    ]
