# Generated by Django 4.0 on 2022-08-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0013_alter_rmsgeneralinformationprocess_hod_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='department',
            field=models.CharField(choices=[('ICT', 'ICT'), ('Communication', 'Communication'), ('Finance', 'Finance'), ('Community', 'Community')], max_length=30),
        ),
    ]
