# Generated by Django 4.0 on 2022-08-03 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0014_alter_rmsgeneralinformationprocess_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='HOD_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='HOD_email',
            field=models.EmailField(default=datetime.datetime(2022, 8, 3, 7, 55, 9, 559252, tzinfo=utc), help_text='Enter Your email to digitally sign . i.e ben@kws.go.ke', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='HOD_name',
            field=models.CharField(default=datetime.datetime(2022, 8, 3, 7, 55, 20, 822640, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='date_approved_by_department_head',
            field=models.DateField(auto_now=True, default=datetime.datetime(2022, 8, 3, 7, 55, 30, 272495, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
