# Generated by Django 4.0 on 2022-08-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0015_alter_rmsgeneralinformationprocess_hod_approve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='HOD_approve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='HOD_email',
            field=models.EmailField(blank=True, help_text='Enter Your email to digitally sign . i.e ben@kws.go.ke', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='HOD_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='ICTAuthority_email',
            field=models.EmailField(blank=True, help_text='Enter Your email to digitally sign . i.e ben@kws.go.ke', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='Signature',
            field=models.EmailField(help_text='Enter Your email to digitally sign . i.e ben@kws.go.ke', max_length=254),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='date_approved_by_department_head',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
