# Generated by Django 4.0 on 2022-08-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0016_alter_rmsgeneralinformationprocess_hod_approve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmsgeneralinformationprocess',
            name='fully_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
