# Generated by Django 4.0 on 2022-08-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0017_rmsgeneralinformationprocess_fully_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmsgeneralinformationprocess',
            name='HOD_Rejection_Comments',
            field=models.TextField(blank=True, help_text='You can leave blank if no comments', null=True),
        ),
        migrations.AddField(
            model_name='rmsgeneralinformationprocess',
            name='ICT_Rejection_Comments',
            field=models.TextField(blank=True, help_text='You can leave blank if no comments', null=True),
        ),
    ]
