# Generated by Django 4.0 on 2022-08-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0018_rmsgeneralinformationprocess_hod_rejection_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rmsgeneralinformationprocess',
            old_name='HOD_Rejection_Comments',
            new_name='HOD_Remarks',
        ),
        migrations.RenameField(
            model_name='rmsgeneralinformationprocess',
            old_name='ICT_Rejection_Comments',
            new_name='ICT_Remarks',
        ),
    ]
