# Generated by Django 4.0.5 on 2022-08-30 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0008_jsonfield_and_artifact'),
        ('access', '0019_rename_hod_rejection_comments_rmsgeneralinformationprocess_hod_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Request_Process',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.process')),
                ('Nature_of_Request', models.CharField(choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('EMAIL DISTRIBUTION LIST', 'EMAIL DISTRIBUTION LIST')], max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('est_no', models.CharField(max_length=30)),
                ('department', models.CharField(choices=[('ICT', 'ICT'), ('Communication', 'Communication'), ('Finance', 'Finance'), ('Community', 'Community')], max_length=30)),
                ('date_of_service_request', models.DateField()),
                ('reasons_for_request', models.TextField(blank=True, help_text='State your reasons for requesting an email', null=True)),
                ('HOD_name', models.CharField(blank=True, max_length=50, null=True)),
                ('HOD_approve', models.BooleanField(blank=True, default=False, null=True)),
                ('date_approved_by_department_head', models.DateField(auto_now=True, null=True)),
                ('HOD_email', models.EmailField(blank=True, help_text='Enter Your email to digitally sign . i.e ben@kws.go.ke', max_length=254, null=True)),
                ('IT_Authority_name', models.CharField(blank=True, max_length=30, null=True)),
                ('IT_Approve', models.BooleanField(blank=True, default=False, null=True)),
                ('date_approved_by_it', models.DateField(auto_now=True, null=True)),
                ('ITAuthority_email', models.EmailField(blank=True, help_text='Enter Your email to digitally sign . i.e ben@kws.go.ke', max_length=254, null=True)),
                ('ICT_Remarks', models.TextField(blank=True, help_text='You can leave blank if no comments', null=True)),
                ('email_assigned', models.EmailField(blank=True, help_text='Enter the  email that you have assigned to the applicant ', max_length=254, null=True)),
                ('date_email_address_created', models.DateField(auto_now=True, null=True)),
                ('fully_approved', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
