# Generated by Django 4.0.5 on 2022-08-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0020_email_request_process'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_request_process',
            old_name='ICT_Remarks',
            new_name='IT_Remarks',
        ),
    ]
