# Generated by Django 4.0.5 on 2022-09-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0022_email_request_process_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email_Request_Process',
        ),
    ]
