# Generated by Django 4.0.5 on 2022-09-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0023_delete_email_request_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmsgeneralinformationprocess',
            name='applicant',
        ),
    ]
