# Generated by Django 4.0.5 on 2022-10-04 11:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0024_remove_rmsgeneralinformationprocess_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='area',
            field=models.CharField(choices=[('MOUNTAIN CONSERVATION AREA', 'MOUNTAIN CONSERVATION AREA'), ('SOUTHERN CONSERVATION AREA', 'SOUTHERN CONSERVATION AREA'), ('CENTRAL-RIFT CONSERVATION AREA', 'CENTRAL-RIFT CONSERVATION AREA'), ('TSAVOS(TSAVO CONSERVATION AREA)', 'TSAVOS(TSAVO CONSERVATION AREA)'), ('COAST CONSERVATION AREA', 'COAST CONSERVATION AREA'), ('EASTERN CONSERVATION AREA', 'EASTERN CONSERVATION AREA'), ('WESTERN CONSERVATION AREA', 'WESTERN CONSERVATION AREA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='department',
            field=models.CharField(choices=[('ICT', 'ICT'), ('Customer Service', 'Customer Service'), ('Finance', 'Finance'), ('Parks & Reserves', 'Parks & Reserves'), ('Marketing', 'Marketing'), ('Internal Audit', 'Internal Audit'), ('Revenue Protection Unit', 'Revenue Protection Unit')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='station',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ABERDARES', 'ABERDARES'), ('MT KENYA', 'MT KENYA'), ('MWEA NATIONAL RESERVE', 'MWEA NATIONAL RESERVE'), ('AMBOSELI', 'AMBOSELI'), ('NAIROBI', 'NAIROBI'), ('OL DONYO SABUK', 'OL DONYO SABUK'), ('SAFARI WALK', 'SAFARI WALK'), ('ORPHANAGE', 'ORPHANAGE'), ('LAKE NAKURU', 'LAKE NAKURU'), ('HELLS GATE/LONGONOT', 'HELLS GATE/LONGONOT'), ('TSAVO EAST', 'TSAVO EAST'), ('TSAVO WEST', 'TSAVO WEST'), ('CHYULU HILLS', 'CHYULU HILLS'), ('MOMBASA', 'MOMBASA'), ('MALINDI', 'MALINDI'), ('DIANI', 'DIANI'), ('KISITE MPUNGUTI N. PARK', 'KISITE MPUNGUTI N. PARK'), ('SHIMBA HILLS NATIONAL PARK', 'SHIMBA HILLS NATIONAL PARK'), ('MOMBASA MARINE PARK', 'MOMBASA MARINE PARK'), ('ARABUKO SOKOKE NATIONAL  PARK', 'ARABUKO SOKOKE NATIONAL  PARK'), ('WATAMU MARINE N. RESERVE', 'WATAMU MARINE N. RESERVE'), ('KIUNGA MARINR NATIONAL PARK', 'KIUNGA MARINR NATIONAL PARK'), ('TANA RIVER PRIMATE N. RESERVE', 'TANA RIVER PRIMATE N. RESERVE'), ('MERU NATIONAL PARK', 'MERU NATIONAL PARK'), ('SIBILOI NATIONAL PARK', 'SIBILOI NATIONAL PARK'), ('MARSABIT NATIONAL PARK', 'MARSABIT NATIONAL PARK'), ('SOUTHERN ISLANDS NATIONAL PARK', 'SOUTHERN ISLANDS NATIONAL PARK'), ('MT. ELGON N.P', 'MT. ELGON N.P'), ('SAIWA SWAMP N. P.', 'SAIWA SWAMP N. P.'), ('KAKAMEGA FOREST N RESERVE', 'KAKAMEGA FOREST N RESERVE'), ('NASOLOT N RESERVE', 'NASOLOT N RESERVE'), ('CENTRAL ISLAND NATIONAL PARK', 'CENTRAL ISLAND NATIONAL PARK'), ('RUMA N. P', 'RUMA N. P'), ('KISUMU IMPAL', 'KISUMU IMPALA'), ('NDERE ISLANDS NATIONAL PARK', 'NDERE ISLANDS NATIONAL PARK'), ('S.TURKANA', 'S.TURKANA'), ('LAKE ELEMENTEITA', 'LAKE ELEMENTEITA')], max_length=100),
        ),
    ]
