# Generated by Django 4.0.5 on 2022-10-13 09:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0027_alter_rmsgeneralinformationprocess_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rmsgeneralinformationprocess',
            name='station',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ABERDARES', 'ABERDARES'), ('MT KENYA', 'MT KENYA'), ('MWEA NATIONAL RESERVE', 'MWEA NATIONAL RESERVE'), ('AMBOSELI', 'AMBOSELI'), ('NAIROBI', 'NAIROBI'), ('OL DONYO SABUK', 'OL DONYO SABUK'), ('SAFARI WALK', 'SAFARI WALK'), ('ORPHANAGE', 'ORPHANAGE'), ('LAKE NAKURU', 'LAKE NAKURU'), ('HELLS GATE/LONGONOT', 'HELLS GATE/LONGONOT'), ('TSAVO EAST', 'TSAVO EAST'), ('TSAVO WEST', 'TSAVO WEST'), ('CHYULU HILLS', 'CHYULU HILLS'), ('MOMBASA', 'MOMBASA'), ('MALINDI', 'MALINDI'), ('DIANI', 'DIANI'), ('KISITE MPUNGUTI N. PARK', 'KISITE MPUNGUTI N. PARK'), ('SHIMBA HILLS NATIONAL PARK', 'SHIMBA HILLS NATIONAL PARK'), ('MOMBASA MARINE PARK', 'MOMBASA MARINE PARK'), ('ARABUKO SOKOKE NATIONAL  PARK', 'ARABUKO SOKOKE NATIONAL  PARK'), ('WATAMU MARINE N. RESERVE', 'WATAMU MARINE N. RESERVE'), ('KIUNGA MARINE NATIONAL PARK', 'KIUNGA MARINE NATIONAL PARK'), ('TANA RIVER PRIMATE N. RESERVE', 'TANA RIVER PRIMATE N. RESERVE'), ('MERU NATIONAL PARK', 'MERU NATIONAL PARK'), ('SIBILOI NATIONAL PARK', 'SIBILOI NATIONAL PARK'), ('MARSABIT NATIONAL PARK', 'MARSABIT NATIONAL PARK'), ('SOUTHERN ISLANDS NATIONAL PARK', 'SOUTHERN ISLANDS NATIONAL PARK'), ('MT. ELGON N.P', 'MT. ELGON N.P'), ('SAIWA SWAMP N. P.', 'SAIWA SWAMP N. P.'), ('KAKAMEGA FOREST N RESERVE', 'KAKAMEGA FOREST N RESERVE'), ('NASOLOT N RESERVE', 'NASOLOT N RESERVE'), ('CENTRAL ISLAND NATIONAL PARK', 'CENTRAL ISLAND NATIONAL PARK'), ('RUMA N. P', 'RUMA N. P'), ('KISUMU IMPAL', 'KISUMU IMPALA'), ('NDERE ISLANDS NATIONAL PARK', 'NDERE ISLANDS NATIONAL PARK'), ('S.TURKANA', 'S.TURKANA'), ('LAKE ELEMENTEITA', 'LAKE ELEMENTEITA')], max_length=100),
        ),
    ]
