# Generated by Django 4.0.5 on 2022-09-19 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0008_jsonfield_and_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_User_Sunsystem_Process',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.process')),
                ('User_Name', models.CharField(max_length=100)),
                ('Initials', models.CharField(help_text='Must be 3 letters', max_length=100)),
                ('est_no', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('ICT', 'ICT'), ('Communication', 'Communication'), ('Finance', 'Finance'), ('Community', 'Community')], max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('Station_Park', models.CharField(max_length=100)),
                ('Unit_Head_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Unit_Head_Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Unit_Head_Email', models.EmailField(blank=True, help_text='Enter Your email to digitally sign . i.e ben@kws.go.ke', max_length=254, null=True)),
                ('date_approved_by_Unit_head', models.DateField(auto_now=True, null=True)),
                ('HOD_name', models.CharField(blank=True, max_length=50, null=True)),
                ('HOD_approve', models.BooleanField(blank=True, default=False, null=True)),
                ('date_approved_by_department_head', models.DateField(auto_now=True, null=True)),
                ('HOD_email', models.EmailField(blank=True, help_text='Enter Your email to digitally sign . i.e ben@kws.go.ke', max_length=254, null=True)),
                ('Checked_by', models.CharField(blank=True, max_length=30, null=True)),
                ('Created', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateField(auto_now=True, null=True)),
                ('Expiry', models.BooleanField(blank=True, default=False, null=True)),
                ('Expiry_Date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
