# Generated by Django 4.0.5 on 2022-09-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newusersunsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user_sunsystem_process',
            name='Expiry_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
