# Generated by Django 4.0.5 on 2022-10-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newusersunsystem', '0002_alter_new_user_sunsystem_process_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user_sunsystem_process',
            name='department',
            field=models.CharField(choices=[('ICT', 'ICT'), ('Customer Service', 'Customer Service'), ('Finance', 'Finance'), ('Parks & Reserves', 'Parks & Reserves'), ('Marketing', 'Marketing'), ('Internal Audit', 'Internal Audit'), ('Revenue Protection Unit', 'Revenue Protection Unit')], max_length=100),
        ),
    ]
